### ISSUE TITLE
separate out renderer and figure

### ISSUE THREAD

**Issue by jasongrout** [jovyan/pythreejs#10]
We've seen for a long time that since we create a new renderer each time we display a figure, we end up blowing past the browser webgl context limits.  Instead, we should display a _figure_ that takes a renderer, scene, and camera.  That way it is easy to reuse a renderer for different displays.  On the js side, the renderer should maybe be created as the model is created and attached to the model, as we really want a singleton renderer, not one for each view.

**Comment by vidartf** [comment]
Closing as superseded by the renderer pool.
