### ISSUE TITLE
[autogen wrappers] the autogen wrappers branch seems to add a dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [jovyan/pythreejs#117]
on the data widgets.

Is this really required for core pythreejs?

**Comment by vidartf** [comment]
I was initially unsure, which is why I explicitly brought it up for discussion in https://github.com/jovyan/pythreejs/pull/113. Not much discussion followed, but the argument for adding the dependency is that pythreejs can then share data sources with widgets from other packages (i.e. with a single upload).

**Comment by vidartf** [comment]
That said, it should be possible to turn this into an optional dependency if we're careful.

**Comment by SylvainCorlay** [comment]
I really like the data widget, but I am unsure this should be a dependency. Ideally, we should be able to wire any widget with a data widget using e.g. jslink...

**Comment by vidartf** [comment]
> I really like the data widget, but I am unsure this should be a dependency.

I think I have an idea for how to make this optional. I'll give it a spin to see how hard it is.

> Ideally, we should be able to wire any widget with a data widget using e.g. jslink...

As far as I understand jslink (feel free to correct if wrong), it does not prevent syncs from happening e.g.:
```
pyA <--> jsA
pyB <--> jsB

jslink jsA <--> jsB

update pyA ==sync==> jsA updates --> jsB updates ==sync==> pyB
```
Which is one sync more than needed, and which can be quite expensive it involves a large array. Also, depending on how the objects are set up and/or serialized, there might occur a memory copy between jsA and jsB.

**Comment by vidartf** [comment]
> I think I have an idea for how to make this optional. I'll give it a spin to see how hard it is.

After looking further into this, the best way to make data widgets option would be to split the data widget npm package into two parts:
   1. One part that implements the general union serializer (serializer for something that can be either an array or a widget) and functions for getting/setting/observing data. This will be a non-widget, npm only dependency.
   2. One part that implements the actual data widget classes.

The major consequence of this will be that it is harder to introspect the source of the data, especially `instanceof` will be unusable. This should be OK for pythreejs though (and packages that need it will have to depend on part 2).

**Comment by vidartf** [comment]
Note: This will only enable us to not need the data widgets to be installed as a forntend extension, we will still need to have a dependency on the python package in order for the traits specification to check out OK...

**Comment by maartenbreddels** [comment]
Did you think of `traitlets.Instance('package.ClassName')`, like what I did in ipyvolume for pythreejs? And on the js side we could do sth like `value.isDataWidget` like I believe threejs is now doing. Then we don't need the js package nor the py package.

**Comment by vidartf** [comment]
@maartenbreddels The serializers would still need to be referenced in the Python side, and so would the validation/constraints. Again, this could possibly be split into two packages, but at this point I want to break this down a little.

@SylvainCorlay What is your main arguments for not having data widgets as a dependency? Depending on what the concerns are, different solutions are possible. E.g. if the only concern is that users will have to install/enable another frontend extension we can fix that reasonably easy (and this will not be a problem for jupyterlab). If this is a minimalist effort, i.e. for pythreejs to have as few dependencies as possible as a general design philosophy, then I'm not sure if I'll be able to come up with a solution (but I'm listening if anybody has some ideas).

**Comment by vidartf** [comment]
Looking at this from afar, and thinking a little more about Sylvain's inital suggestion, the best option might be to extend/improve jslink, such that when a jslink source is set, it:
 - Syncs itself over Comm (like now)
 - Sets the link target values on both backend and frontend side, ***without*** syncing the values over Comm (i.e. the backend side of the link sets the backend target, and the frotend side of the link sets the frontend target). This would require there to be a way to set a value on either side in a way that does not trigger a sync.

This might be the best solution in general, and could possibly be useful for other things than just data widgets. We might want this to need a flag / different function though, as this can cause an invalid state if the source/target serializers differ significantly.

**Comment by maartenbreddels** [comment]
I think that link behaviour would be nice, but I think the python dependancy wouldn't be needed, and this may be an easier solution. I don't see this python dep as a huge problem, but you could do a check if the datawidget can be imported, and when possible, forward the calls to the serializer/deserializer. If datawidget cannot be imported, you just keep the default ndarray (de)serializer.

**Comment by SylvainCorlay** [comment]
> Syncs itself over Comm (like now)
> Sets the link target values on both backend and frontend side, without syncing the values over Comm (i.e. the backend side of the link sets the backend target, and the frotend side of the link sets the frontend target). This would require there to be a way to set a value on either side in a way that does not trigger a sync.

I think that this would lend itself to many potential race conditions and is probably not worth it.

The whole thing depends on what we want to minimize. Do we want to minimize latency (then jslink is fine), or the size of messages (then any link is bad currently), or the time spent serializing (then with binary serialization, this is *OK*) most of the time even with jslink because it is basically a memcopy.

My argument against having the data widget as a dependency was more an argument of principle. I find it very striking the bqplot and ipyvolume can be linked in the example here https://ipyvolume.readthedocs.io/en/latest/bqplot.html without knowing at all about each other and really saw that as a really something I like in ipywidgets. As much as I like both libraries a lot, I don't think that one should depend on another...

Let me know what you think.

**Comment by vidartf** [comment]
Thanks for the explanation. As far as I was concerned, data widgets should not be considered as a package that ***uses*** ipywidgets, but rather a package that ***extends*** ipywidgets. One could argue that some of this functionality should go into the main repository, but I prefer to separate areas of responsibility (data widgets would hopefully be a stable package after some initial development). If the philosophy is that ipywidgets should be the only shared dependency between packages, I should probably start lobbying for getting the main features into ipywidges.

The main problem that data widgets are supposed to solve are two-fold:
 - Provide a set of common, re-usable serializers for arrays (buffer AND metadata) on both kernel and frontend side.
 - Allow for optimal transfer of data in cases where the data is large. This includes only transferring the data once if it is shared between several consumers (big messages will take a long time to transfer, but will also block the message channel, causing latency of other high-priority messages). It also entails that duplicate copies of the same data in memory should be avoided.

The last points means that one ndarray on the python side should map uniquely to one ndarray.js structure on the JS side. I cannot see how this can be achieved without having a shared dependency, but again, I'm open to anyone with an idea.

PS: If possible, data widgets should also handle views efficiently, but this is a harder problem. However, I'd prefer any design to also be able to support this further down the line.

**Comment by SylvainCorlay** [comment]
This also touches the discussion on 

 - https://github.com/jupyter-widgets/traittypes.
 - the choice for a binary transfer format.

I am not sure all projects need the same ndarrayjs library but we can definitely decide to elect one implementation as the default.

**Comment by vidartf** [comment]
Discussed this over video chat yesterday. A brief summary:
 - A dependency here is OK as long as it will not fail if the data widgets are not available as a frontend extension.
 - There were suggestions to look more into using Apache Arrow in addition/instead of scijs ndarray.
