### ISSUE TITLE
NameError: name 'MeshStandardMaterial' is not defined

### ISSUE THREAD

**Issue by nirgivon** [jovyan/pythreejs#128]
Trying to use examples from the examples folder.
This error always come up.

Sample: from  pythreejs/examples/test.ipynb 
from pythreejs import *
from IPython.display import display

# Materials
mat = MeshStandardMaterial(color='#ff0000')
mat_green = MeshStandardMaterial(color='#00ff00')
mat_blue = MeshStandardMaterial(color='#0000ff')

Error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-ce0e09416a2e> in <module>()
      1 # Materials
----> 2 mat = MeshStandardMaterial(color='#ff0000')
      3 mat_green = MeshStandardMaterial(color='#00ff00')
      4 mat_blue = MeshStandardMaterial(color='#0000ff')

NameError: name 'MeshStandardMaterial' is not defined

**Comment by vidartf** [comment]
Is this on latest release or on master?

**Comment by nirgivon** [comment]
Installed from master 1 hour ago.

pip install pythreejs
jupyter nbextension install --py --symlink --sys-prefix pythreejs
jupyter nbextension enable --py --sys-prefix pythreejs

**Comment by nirgivon** [comment]
using jupyter lab

**Comment by vidartf** [comment]
```
pip install pythreejs
jupyter nbextension install --py --symlink --sys-prefix pythreejs
jupyter nbextension enable --py --sys-prefix pythreejs
```
These instructions are for installing the latest release. The examples in master will not work with that. To install from master, you should clone the repository and run `pip install -e .` in the repo root.

**Comment by nirgivon** [comment]
Thanks!
