### ISSUE TITLE
" Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"

### ISSUE THREAD

**Issue by SylvainCorlay** [jovyan/pythreejs#129]
Running `npm install` in js yields

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

at the current tip of master.

**Comment by vidartf** [comment]
There are some issues in master that needs resolution here, but for the install / build code (which is giving the error reported), I'd say you need to update your version of Node: http://node.green/#ES2015-bindings-const
