### ISSUE TITLE
"Failed to display Jupyter Widget" error

### ISSUE THREAD

**Issue by mkhorton** [jovyan/pythreejs#132]
Apologies for using your issues page as tech support, but I'm having a lot of trouble getting pythreejs working, and have no idea how to start debugging an nbextension. It's unclear what the recommended route is for the current state of the project, whether I'm making a mistake in the installation, or if it's a bug.

Whenever I try to run any sample code, e.g. from the examples folder, I get:

```
Failed to display Jupyter Widget of type PreviewWidget.
If you're reading this message in Jupyter Notebook or JupyterLab, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled.
```

I've tried:

```
pip install pythreejs
jupyter nbextension install --py --symlink --sys-prefix pythreejs
jupyter nbextension enable --py --sys-prefix pythreejs
```

I've also tried a git clone:

```
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix pythreejs
jupyter nbextension enable --py --sys-prefix pythreejs
```

In both cases, `jupyter nbextension list` gives:

```
Known nbextensions:
  config dir: /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/etc/jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled
      - Validating: OK
```

I'm using Python 3.6.1, Jupyter 4.3.0, and also tried Jupyter Lab. I also tried an `npm run build` and `npm run autogen` inside the js folder. Whatever permutation I've tried, I also get this 'Failed to display' error.

Many thanks for any help you can give!

**Comment by mkhorton** [comment]
(Though I think in one instance the error was `Failed to display Jupyter Widget of type BoxGeometry.`)

**Comment by vidartf** [comment]
The best way to debug these things is to:
 - Check the browser console for any interesting log output.
 - Check the notebook server log for any interesting output.

Other than that, the stable release and master are currently very different (rewrite in master), so I would expect different errors. I'm not sure if I would recommend master yet for non-developers. You might want to ensure you completely remove any traces of the nb extension before trying a fresh install (`jupyter nbextension uninstall --sys-prefix --py pythreejs`). I would also avoid the symlink flag when doing a non-developer install.

Try out these things, and let me know what you find!

**Comment by mkhorton** [comment]
I am getting a 404 with:

`[W 14:50:43.648 NotebookApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js?v=20171109144658 (::1) 1.49ms referer=http://localhost:8889/notebooks/Untitled.ipynb`

Will continue to investigate + let you know if I can get it fixed.

Having the same issue on a completely independent (third-party) Jupyter install too, so it's not just my machine ... was trying to install from master because I'm hoping to write mini reusable module that users pythreejs for rendering some of our scientific data, but completely understand if the rewrite isn't ready for prime time yet. Will check back in a bit :)

**Comment by chenray844** [comment]
Hi, when i want to use this project in jupyter, i get some error in web-console, and the widget is not shown. 
```
load_extensions 
Arguments { 0: "jupyter-threejs/extension", 1: "jupyter-js-widgets/extension", … }
utils.js:60
Loading extension: jupyter-threejs/extension
utils.js:37
Loading extension: jupyter-js-widgets/extension
utils.js:37
Session: kernel_created (a10ae346-99fc-4fae-9fb6-314fd726ec26)
session.js:54
Starting WebSockets: ws://localhost:8888/api/kernels/c9f689ac-88b7-42c1-85be-33b5d2c801f7
kernel.js:459
Kernel: kernel_connected (c9f689ac-88b7-42c1-85be-33b5d2c801f7)
kernel.js:103
Kernel: kernel_ready (c9f689ac-88b7-42c1-85be-33b5d2c801f7)
kernel.js:103
created renderer
jupyter-threejs.js:19
THREE.WebGLRenderer 75
three.js:24414
renderer 
Object { cid: "c10", attributes: {…}, _changing: false, _previousAttributes: {}, changed: {}, id: undefined, _pending: false, widget_manager: {…}, model_id: "e730188299c546b29a12dc4d15963f1d", views: {…}, … }
 
Object { uuid: "6DF5E9AF-4FAA-4474-8C65-25D7E028B09B", name: "", type: "Scene", parent: null, children: […], up: {…}, position: {…}, rotation: {…}, quaternion: {…}, scale: {…}, … }
 
Object { uuid: "E847EFEC-1691-4899-B22D-4CE38EC2D56A", name: "", type: "PerspectiveCamera", parent: {…}, children: [], up: {…}, position: {…}, rotation: {…}, quaternion: {…}, scale: {…}, … }
jupyter-threejs.js:71
TypeError: this.scene is undefined
[Learn More]
jupyter-threejs.js:113
Error: Could not create a view for model id 55eec408558b437c90e42dcb81ab1b64
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
Error: Could not create child view
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
Error: Could not create a view for model id 8693fce8652e492a919b961d296a1f8b
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
Error: Could not create child view
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
Error: Could not create a view for model id e730188299c546b29a12dc4d15963f1d
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
Error: Could not create view
Stack trace:
promiseRejection@http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180119163957:21472:27
utils.js:119
TypeError: this.options.render_frame is not a function
[Learn More]
jupyter-threejs.js:326

```

Install with commands 
```
pip3 install pythreejs
jupyter nbextension install --py --symlink --sys-prefix pythreejs
jupyter nbextension enable --py --sys-prefix pythreejs
```

and 
```
jupyter nbextension list
Known nbextensions:
  config dir: /Users/Raymond/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /Library/Frameworks/Python.framework/Versions/3.6/etc/jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK

```

can some one give me some advice to fix this error? 
thanks.

**Comment by chenray844** [comment]
I just start a new running env, and run `jupyter nbextension enable pythreejs --py --sys-prefix` before `jupyter notebook`, and it's all right. 
![img](https://user-images.githubusercontent.com/2977266/35219279-ef945248-ffac-11e7-9a04-12f08f1a833b.png)

thanks 👍

**Comment by vidartf** [comment]
I'm going to close this as resolved. Feel free to make a comment if I have missed something in the thread that has not been resolved, or preferably open up a new issue linking back to this one.

**Comment by jmmshn** [comment]
Just wanted to put this somewhere for future reference:
The widget might not always work when you install the labextension using:
```
jupyter labextension install jupyter-threejs
```

It seems that running
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
fixed the issue.

**Comment by mkhorton** [comment]
Thanks @jmmshn, mystery solved!

**Comment by jasongrout** [comment]
You need to install both for it to work.
