### ISSUE TITLE
Inaccessible ThreeJS functionality

### ISSUE THREAD

**Issue by janba** [jovyan/pythreejs#142]
First of all, thanks for this great project. I am very pleased to be able to render graphics in a notebook.

Some of the features of ThreeJS seem to be inaccessible from PyThreeJS.  Specifically in JS:
```
material = new THREE.ShaderMaterial( {
  uniforms: {},
  vertexShader: document.getElementById( 'vertexShader' ).textContent,
  fragmentShader: document.getElementById( 'fragmentShader' ).textContent
} );
material.extensions.derivatives = true;
```

but we do not seem to be able to do that from Python because

>  'ShaderMaterial' object has no attribute 'extensions'

So, my question is if 'extensions' is simply not wrapped? If so, is there a workaround?

Cheers
Andreas

**Comment by vidartf** [comment]
Which version of pythreejs are using? A lot of these things are fixed in master, which I'm hoping to get a beta/RC of soon.

**Comment by janba** [comment]
I was using 0.4.1.  I just installed from the git repo and yes - now it works. Thanks! 
Looking forward to the release. Is there a timeline :-) ?

**Comment by vidartf** [comment]
I'm probably going to push a beta before christmas, but there are some changes I want to get in first. We'll see if I can make it!
