### ISSUE TITLE
conda package for release 1.0.0*

### ISSUE THREAD

**Issue by tpaviot** [jovyan/pythreejs#147]
any chance that the conda-forge channel is updated with the lastest pythreejs version ?

Trying to run the examples for the latest version, I faced the same issue than #136. I could not test your latest release, and had to downgrade to 0.4.

Great job anyway.

**Comment by vidartf** [comment]
The conda-forge package is up to date with the latest stable release. I'll probably do a beta on it once other issues have been sorted. Final release will definitely be put on conda-forge.

I you want to help, I'd much appreciate the full installation outputs from `pip install -v --pre pythreejs`, and the relevant command for the frontend-extension (`jupyter nbextension enable --py [--sys-prefix | --user | --system] pythreejs` for classic, `jupyter labextension install jupyter-threejs@beta` for lab). I'd also appreciate any outputs from the browser console (typically you can get this by pressing F12) and/or server log.

**Comment by tpaviot** [comment]
Here is a gist with the ouput from pip install. https://gist.github.com/tpaviot/b4059aeb2a9554121f52ff887df5ce2f

**Comment by tpaviot** [comment]
However,

<pre>
>>> import pythreejs
>>> pythreejs.__version__
'0.4.1'
</pre>

**Comment by tpaviot** [comment]
and `pip install .` fails see https://gist.github.com/tpaviot/7d3a61dfb1a3411068900e084ce4ea71

**Comment by tpaviot** [comment]
Tried for a couple of hours to get the latest release working, or even installed, on my windows machine. Not succeeded. Much looking forward a conda package.
