### ISSUE TITLE
Failed to display Jupyter Widget of type Preview

### ISSUE THREAD

**Issue by tpaviot** [jovyan/pythreejs#148]
Just installed release 1.0.0b3 from source. pythreejs installed successfully, nbextension succesffully installed/enabled as well. Running examples, each time the renderer is called, I get the following exception:

<code>
Failed to display Jupyter Widget of type Preview.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

</code>

The web console (Firefox on Ubuntu 17.10) reports that the extension is not loaded.

<code>
Failed to load extension: Array [ "nbextensions/pythreejs" ] Error: Script error for "nbextensions/pythreejs"
http://requirejs.org/docs/errors.html#scripterror
Stack trace:
makeError@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165:17
onScriptError@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1732:36
 utils.js:62
</code>

What did I miss ?

**Comment by vidartf** [comment]
The error seems to be with loading the extension in the browser, which would explain the messages. This error message doesn't make much sense though: `Failed to load extension: Array [ "nbextensions/pythreejs" ]`. It should be trying to load `jupyter-threejs` on the JS side, not anything with `pythreejs` in the name. E.g. I see:
```
load_extensions   Arguments { 0: "jupyter-js-widgets/extension", 1: "jupyter-threejs/extension", … }
```
in my console output.

There might be conflicting versions of the frontend extension installed. What is the output of `jupyter nbextension list` ?

**Comment by vidartf** [comment]
For completion's sake: Would you mind specifying which example you use, and sharing the full console output?

Thanks for helping to debug this 👍

**Comment by vidartf** [comment]
(OS and browser name/version could also be useful for trying to reproduce this).

**Comment by tpaviot** [comment]
Output from `jupyter nbextension list`:

```
(py3js100c) thomas@thomas-X756UVK:~/Devel/pythreejs/examples$ jupyter nbextension list
Known nbextensions:
  config dir: /home/thomas/.jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK
      pythreejs  enabled 
      - Validating: problems found:
        - require?  X pythreejs
  config dir: /home/thomas/miniconda3/envs/py3js100c/etc/jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK
```

Seems a requirement is not satisfied.

**Comment by tpaviot** [comment]
OS: Ubuntu 17.10, browser FireFox 57.0.1 64 bits

**Comment by tpaviot** [comment]
Hi tried to reinstall/reenable the jupyter extension, but I still get the same issue:
```
(py3js100c) thomas@thomas-X756UVK:~/Devel/pythreejs/examples$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
Installing /home/thomas/miniconda3/envs/py3js100c/lib/python3.6/site-packages/pythreejs/static -> jupyter-threejs
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable pythreejs --py --sys-prefix
    
(py3js100c) thomas@thomas-X756UVK:~/Devel/pythreejs/examples$  jupyter nbextension enable pythreejs --py --sys-prefix
Enabling notebook extension jupyter-threejs/extension...
      - Validating: OK
(py3js100c) thomas@thomas-X756UVK:~/Devel/pythreejs/examples$ jupyter nbextension list
Known nbextensions:
  config dir: /home/thomas/.jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK
      pythreejs  enabled 
      - Validating: problems found:
        - require?  X pythreejs
  config dir: /home/thomas/miniconda3/envs/py3js100c/etc/jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK
```


```

**Comment by vidartf** [comment]
@tpaviot From the `jupyter nbextension list` output, I can see that pythreejs is installed/configured multiple times, once on a user level, and once on a conda env level, and with different names. Follow these steps to manually clear pythreejs from your config:

1. Open `/home/thomas/.jupyter/nbconfig/notebook.json`, and remove both `jupyter-threejs` and `pythreejs` from the `load_extensions` entry.
2. Run `jupyter --paths`, and for each path in the `data` category (except the conda one), go into the `nbextensions` sub-folder, and delete any folders named `jupyter-threejs` or `pythreejs`.

Hopefully that should work.

**Comment by tpaviot** [comment]
Thanks for your help. I cleaned up the installation as you told, now I have
```
(py3js100) thomas@thomas-X756UVK:~/Devel/pythreejs$ jupyter nbextension list
Known nbextensions:
  config dir: /home/thomas/miniconda3/envs/py3js100/etc/jupyter/nbconfig
    notebook section
      jupyter-threejs/extension  enabled 
      - Validating: OK
```
Unfortunately, I still have the same issue. I tried to open/read the console, but can't get any explicit information.

I'm on Ubuntu 17.10, I will try on an Ubuntu 16.04 and report the installation/execution process.

**Comment by tpaviot** [comment]
Ok, I fixed my installation. This was indeed a conflict between different jupyter installations.

Note: jupyter must ne bo installed in the root conda environment.
