### ISSUE TITLE
ParametricGeometry is not defined

### ISSUE THREAD

**Issue by AresAndy** [jovyan/pythreejs#151]
I am trying to run the example displayed on the README of this project, and it fails saying:

NameError                                 Traceback (most recent call last)
<ipython-input-2-9e3e48091bae> in <module>()
     12 """
     13 
---> 14 surf_g = ParametricGeometry(func=f)
     15 surf = Mesh(geometry=surf_g, material=LambertMaterial(color='yellow', side='FrontSide'))
     16 surf2 = Mesh(geometry=surf_g, material=LambertMaterial(color='green', side='BackSide'))

NameError: name 'ParametricGeometry' is not defined

**Comment by vidartf** [comment]
Note: The current README on master is not necessarily compatible with the latest stable release (same for the examples). See the [tree at the 0.4.0 tag](https://github.com/jovyan/pythreejs/tree/0.4.0) for a view that is compatible with the last stable.

If you still have issues after that, please include the version of pythreejs you have installed. `python -c "from pythreejs import version_info; print (version_info)"` should be helpful.

**Comment by vidartf** [comment]
With 1.0.0 released, I'm going to close this as resolved.

**Comment by AresAndy** [comment]
Ok, but please keep the documentation up to date, inconsistencies brings interested folk away from plausibly awesome projects ;) , an attitude I usually find around non super-popular Python related projects
