### ISSUE TITLE
Warning in Animation.ipynb on Unbuntu 17.10/FF58

### ISSUE THREAD

**Issue by tpaviot** [jovyan/pythreejs#164]
Running the Animation.ipynb, I get the following warning (cell nbr 6):
```
positon_track = VectorKeyframeTrack(name='.position',
    times=[0, 2, 5],
    values=[10, 6, 10,
            6.3, 3.78, 6.3,
            -2.98, 0.84, 9.2,
           ])
rotation_track = QuaternionKeyframeTrack(name='.quaternion',
    times=[0, 2, 5],
    values=[-0.184, 0.375, 0.0762, 0.905,
            -0.184, 0.375, 0.0762, 0.905,
            -0.0430, -0.156, -0.00681, 0.987,
           ])
/home/../python3.6/site-packages/ipydatawidgets/ndarray/serializers.py:62: UserWarning: Cannot serialize (u)int64 data, Javascript does not support it. Casting to (u)int32.
  warnings.warn('Cannot serialize (u)int64 data, Javascript does not support it. '
```

**Comment by vidartf** [comment]
That's basically saying: "I see that you passed me integers. Javascript only supports 32-bit ints, so I'm going to have to cast it to that. If you have any numbers that do not fit into 32-bits, they will loop around".

That being said, I do not see this warning, so I'm assuming one of your dependencies differ from what I have. Would you mind doing a `conda list` or `pip list` (as appropriate) for the kernel environment, and paste the output?

**Comment by vidartf** [comment]
@tpaviot Do you have any feedback here?

**Comment by MannyKayy** [comment]
I have the same issue...  my [docker setup](https://github.com/MannyKayy/docker/blob/master/Dockerfile) lists all my dependencies
