### ISSUE TITLE
manipulate camera bound to orbit controls

### ISSUE THREAD

**Issue by mzhng** [jovyan/pythreejs#166]
Is it possible to manually update the position and rotation of a camera that is bound to an instance of OrbitControls? I believe in the original threejs implementation, one can call `controls.update()` after updating the camera to make it work properly, but it seems the `update` method is not available in `pythreejs.OrbitControls`. I can update the camera's attributes and see the change in the displayed scene, but when I click on it, it seems the orbit controls take over again and reset all changes I applied to the camera.

**Comment by vidartf** [comment]
For version 1 beta:
Normally you would do this via `camera.quaternion` or `camera.rotation`. There are also the utility functions `rotateX`/`rotateY`/`rotateZ`, `lookAt` and `setRotationFromMatrix`. Again, these are all on the `Camera` instance.

For older:
You can manipulate `camera.quaternion`, or use the utility function `quaternion_from_rotation` or `look_at`.

Does this answer your question?

**Comment by vidartf** [comment]
Closing as answered.
