### ISSUE TITLE
Not all threejs properties get synced to backend

### ISSUE THREAD

**Issue by maartenbreddels** [jovyan/pythreejs#173]
From the js console i do:
```javascript
camera.position.x = 2
camera.ipymodel.syncToModel()
```
But only the properties listed in `propsDefinedByThree` get synced to the backend:
<img width="628" alt="screen shot 2018-03-29 at 14 44 38" src="https://user-images.githubusercontent.com/1765949/38089458-c3564060-335f-11e8-985d-0aef9c8a994e.png">

The other way around it works without issues, I can set camera.position from the Python side, and it gets synced back.

**Comment by maartenbreddels** [comment]
`camera.ipymodel.syncToModel(true)` seems to do it, is that proper usage? Can you explain the idea behind this?

**Comment by vidartf** [comment]
There are some properties that are marked as `set_by_three`. These are the ones that get synced without the argument. This is basically an optimization to reduce the numbers of compares on changes.

**Comment by vidartf** [comment]
Closing as answered, feel free to comment if you disagree :)
