### ISSUE TITLE
Scene.background default not null/None and None does not translate to null on the frontend

### ISSUE THREAD

**Issue by maartenbreddels** [jovyan/pythreejs#176]
[According to the docs](https://threejs.org/docs/#api/scenes/Scene) the default background for a Scene should be null. However, when I explicitly set it to None, it translates to sth non-null on the frontend:
<img width="935" alt="screen shot 2018-04-11 at 10 37 14" src="https://user-images.githubusercontent.com/1765949/38605826-b4556ef0-3d74-11e8-9383-10a920f24a10.png">

**Comment by vidartf** [comment]
The [current definition](https://github.com/jovyan/pythreejs/blob/e1798b8eacb038a318510e4f721481086a5b7224/js/scripts/three-class-config.js#L1176) of `Scene.background` is simply a color. It is currently marked as nullable, but I think that only causes the default of `THREE.Color()` to be used.

**Comment by maartenbreddels** [comment]
The generated python code for Scene gives me:
```python
background = Unicode("#ffffff", allow_none=True).tag(sync=True)
```
is that expected

**Comment by vidartf** [comment]
> is that expected

Yes, but the JS side is wrong. I'm working on a fix.

**Comment by vidartf** [comment]
PS: It is a `Unicode` trait in order to support all the different strings for `THREE.Color`: https://threejs.org/docs/#api/math/Color

**Comment by vidartf** [comment]
By the way, what are you trying to achieve by setting the background to `None`?

**Comment by vidartf** [comment]
If you are trying to achieve a transparent background, you will also need to set the `clearOpacity` of the renderer to 0.

**Comment by maartenbreddels** [comment]
Well, in ipyvolume I created my own scene, now that I'm using a scene created from pythreejs, it has a background color, which causes (I think) in one of my render passes to clear the framebuffer with a white color. Before it didn't do that, so that's why I noticed.

**Comment by vidartf** [comment]
Oh, you're using your own renderer, so then the pythreejs renderer is not relevant.

**Comment by vidartf** [comment]
@maartenbreddels Let me know if #177 fixed the problem or not!

**Comment by maartenbreddels** [comment]
Yes, background is null now, but the generated code still has background's default set to '#ffffff', but you said that is expected, I don't understand why? And if the threejs docs says null is the default, shouldn't the default be None for the Python side?

**Comment by vidartf** [comment]
The generated code is expected based on the configuration linked.

The default was set to white before I got null support, but was kept as a jupyter specific change as that is the default background color of notebooks. When set to `null`, the default background would be the clear color which defaults to black. Does the default white make sense, or do you think it should be set back to `None`?

**Comment by maartenbreddels** [comment]
I'd say, we should have a default that is transparant, so it uses the background of whatever the theme is. That would mean we'd have to have a non-default alpha=True for the [Renderer](https://threejs.org/docs/#api/renderers/WebGLRenderer) .. What do you think?

**Comment by vidartf** [comment]
I would say transparent is a bad default:
 - Adding the alpha channel has a (small?) performance penalty
 - Depending on the theme, the background might combine poorly with the colors in the scene, e.g. black text/grids on a black background.

**Comment by vidartf** [comment]
PS: If you want to use theme colors in widgets, I would recommend setting up a library that defines color constants based on CSS vars. These can then be dynamically calculated on the JS side. E.g.:

```python
jslink((scene, 'background'), (themecolors, '--jp_layout_color0'))
```

**Comment by maartenbreddels** [comment]
I'd say what seems like a good default for now, but I think that jslink example is something to think about. Maybe mention the white default in the docs, as deviating from the defaults in threejs?

**Comment by vidartf** [comment]
Are you saying this isn't enough? 😅 
http://pythreejs.readthedocs.io/en/latest/api/scenes/Scene_autogen.html#pythreejs.Scene.background

**Comment by maartenbreddels** [comment]
Ok, that will do :)
