### ISSUE TITLE
Appending objects to scene.children

### ISSUE THREAD

**Issue by nlooije** [jovyan/pythreejs#26]
per this [TODO](https://github.com/jovyan/pythreejs/blob/master/pythreejs/pythreejs.py#L134), to add objects to `scene.children` from a linked function it is not possible to simply do:

> scene.children.append(object)

instead according to the example notebook, we use:

> scene.children = list(scene.children) + [point]

First, why is this as i don't understand why? and, second, I would propose to allow the use of the first method as it is typical Python usage.

**Comment by SylvainCorlay** [comment]
Yes, it is not really a problem with PyThreejs so much as it is a problem with traitlets. 

Trait attributes don't send notifications when the values of sub-elements change, but if you re-assign the whole list, a notification will be sent.

One first thing that would make it less confusing fur users is to make `children` a tuple instead of a list. Since it is un-mutable, there is simply no append method. 

Besides, there are already some experiments with eventful list and dicts implementation that would work with traitlets.

**Comment by nlooije** [comment]
Ok, this clarifies a lot already about the reassignment of the list. Thanks!
Is it possible for me to see these experiments? I am very interested

**Comment by SylvainCorlay** [comment]
Sure, you can check out the [eventful.py](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/eventful.py) file in ipywidgets . Although there is a large rework of the traitlets API in progress, and paving the way to descriptors other than TraitType enabling finer-grained events it definitely something we have in mind.

**Comment by nlooije** [comment]
Sorry if it is a bit off-topic but is it possible to use such an eventfullist to define a dynamic list of objects in the scene which can be displayed in a widget? I am trying to generate a widget with objects every time i add an object to the scene using a picker with a 'dblclick' event.

**Comment by SylvainCorlay** [comment]
I guess you could make such a feature work without using the eventfullist. However, it would not be as efficient.

**Comment by nlooije** [comment]
Do you have any hints how i would go about doing that? efficiency is not that important at the moment

**Comment by SylvainCorlay** [comment]
I don't think PyThreejs's scene propagates click events to the backend, but it could be interesting to add this to Pythreejs.In the meantime, you can use a button on the side to test the rest. Then have the handler for the event create the new items of the scene and "inefficiently" append it to the scene.

**Comment by nlooije** [comment]
Coming back to the reassignment 'feature': I would expect `scene.children = list(scene.children)` (i.e. making a simple copy) to also update the scene but this doesn't seem to happen. Is it because this is a shallow copy?

**Comment by vidartf** [comment]
FYI: While the traitlets list issue is still relevant, the current master now exposes the `add` and `remove` functions on `Object3D` (and its subclasses), mirroring the relevant functions on the three.js API. These accept one or more objects, allowing this code to be cleaner. Referring back to the initial example, it would be: `scene.add(object)`.  Note that the old way should still work.
