### ISSUE TITLE
Request TrackballControls

### ISSUE THREAD

**Issue by oliverlee** [jovyan/pythreejs#32]
I guess I'm requesting TrackballControls if you guys have time to add it.

**Comment by jasongrout** [comment]
This should be very similar to the OrbitControls control: https://github.com/jovyan/pythreejs/blob/master/pythreejs/nbextension/pythreejs.js#L353.  Probably mostly a cut and paste.  I'll look at this soon, but of course a PR would speed things along.  You'd also need to include the trackballcontrols js file in the threejs directory.

**Comment by oliverlee** [comment]
I can take a look when I have some time but I'm not in any hurry so it don't expect to get to it soon.

**Comment by jasongrout** [comment]
Fixed by #36.  Thanks again, @yungyuc!
