### ISSUE TITLE
Animation Example

### ISSUE THREAD

**Issue by oliverlee** [jovyan/pythreejs#33]
Listed in the 'Examples to do' section is 'animate something through space'. Can you provide this example first, or suggestions on how to interact with the render loop so that animation can be done completely from the client side?

**Comment by jasongrout** [comment]
In the examples to do, I was thinking of animating from the python side (so basically change coordinates of an object, like is done in one of the first examples).

If you wanted to affect the pythreejs state totally on the client side, it may be best to use the widget infrastructure and jslink to hook things that will change state (on the client side) with pythreejs state. As an example, if you write a widget (python and javascript) that sweeps through a range of values, totally on the client side, then you can hook the values to the state of the pythreejs object.

**Comment by oliverlee** [comment]
Thanks
