### ISSUE TITLE
the camera example doesn't seem to work

### ISSUE THREAD

**Issue by stonebig** [jovyan/pythreejs#42]
on windows/firefox/python3.4/ipywidgets5.1.3/ipython4.2.0/traitlets4.2.1 ...
![jovyan_camera_firefox](https://cloud.githubusercontent.com/assets/4312421/15072928/953c872e-1396-11e6-8288-0083f1740c86.GIF)

the rest is ok.

**Comment by stonebig** [comment]
as a complementary comment, this whole lot series of `jupyter nbextension enable --py ***` is becoming painfull. I hope a Jupyter menu or option would allow to detect and install them all.

````
jupyter-notebook nbextension enable --py --all_that_you_find_and_recognize_via_pip_list
````

**Comment by misolietavec** [comment]
Very weird issue, windows-style. I think, code should be typed, not "screenshooted". It is not clear how the expected result should look like. Anyway, typing this:

```python
geometry = SphereGeometry(radius=4)
# t = ImageTexture(imageuri="")   how can be texture created from empty uri???
material = LambertMaterial(color="green",opacity=0.2,transparent=True)
sphere = Mesh(geometry=geometry,material=material)
point = Mesh(geometry = SphereGeometry(radius=.5),
             material=LambertMaterial(color="red",transparent=False))
c = PerspectiveCamera(position=[0, 7, 7],
        children=[DirectionalLight(color='white', position=[8, 8, 2], intensity=0.5)])
scene = Scene(children=[sphere, point, AmbientLight(color="#777777")])
# p = Picker(event='mousemove', root=sphere)
renderer = Renderer(camera=c, scene = scene, controls=[OrbitControls(controlling=c)])
# coords = Text()   from where is the Text, what should this do???
# display(coords)   we have no Text, so no display...
display(renderer)
``` 
gives big sphere and small red sphere inside, thanks to opacity of bigger sphere (pythreejs 0.3.1).
I do not understand the purpose of Picker here.

Without further explanation from author of this issue there is nothing to do.

**Comment by vidartf** [comment]
Closing this as missing information.
