### ISSUE TITLE
Support THREE.BufferGeometry and BufferAttribute

### ISSUE THREAD

**Issue by abelnation** [jovyan/pythreejs#46]
When dealing with large and complex geometries, it can be much more efficient to instantiate simple BufferGeometries instead of dealing with three.js's higher level Geometry class.

**Comment by martinal** [comment]
Are someone working on this?

**Comment by martinal** [comment]
In not, I'm interested in contributing, although some pointers to where to start would be most appreciated!

**Comment by abelnation** [comment]
Support for BufferGeometries is initially supported in this PR, which is a significant re-work of the pythreejs lib:
https://github.com/jovyan/pythreejs/pull/57

**Comment by martinal** [comment]
Nice! Has it been decided to go with that reworked version? I can test it and report back later.

**Comment by abelnation** [comment]
Will let @jasongrout @SylvainCorlay comment

**Comment by vidartf** [comment]
This is now in via #88.
