### ISSUE TITLE
Renaming of THREE Geometry classes is confusing

### ISSUE THREAD

**Issue by abelnation** [jovyan/pythreejs#47]
Geometry -> PlainGeometry
PlaneGeometry -> SurfaceGeometry
??? -> FaceGeometry

Are these discrepancies necessary?  Perhaps in the python side, `Geometry` base class could be renamed `BaseGeometry`?

**Comment by jasongrout** [comment]
That makes sense to more closely mirror the names in three.js. The Plane->Surface transition was to emphasize to a python user that they could adjust the z-heights of each point (it wasn't *just* a plane).

**Comment by vidartf** [comment]
I think this should be incorporated before making any releases with the autogen branch (since that will be a major breaking update anyway). Especially the `PlaneGeometry` vs `PlainGeometry` is very confusing.
