### ISSUE TITLE
No shadows on PlainGeometry

### ISSUE THREAD

**Issue by jrsmith3** [jovyan/pythreejs#77]
For some reason shadows do not appear on the `PlainGeometry` objects I create, and I cannot figure out how to add it. I've included an example image of a tetrahedron on top of a `BoxGeometry` cube. You can see the cube is lit and also has shadows, but the tetrahedron is not.

Am I missing something? Is there a way to include shadows on a `PlainGeometry` object? Thanks!

![screenshot from 2017-03-06 17 18 56](https://cloud.githubusercontent.com/assets/204215/23632731/091ec852-0291-11e7-98a7-146575d13c0b.png)

I am using `pythreejs` version 0.3.0 from conda-forge. Here's the code for copy/pasting:

```python
vertices = [[0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]

faces = [[0, 2, 1],
    [0, 3, 2],
    [0, 1, 3],
    [3, 1, 2]]

tet = p3js.PlainGeometry(vertices=vertices, faces=faces)
box = p3js.BoxGeometry(height=1, width=1, depth=1)

mat_red = p3js.LambertMaterial(color='red')

m_tet = p3js.Mesh(geometry=tet, material=mat_red, position=[-0.5, -0.5, 0.5])
m_box = p3js.Mesh(geometry=box, material=mat_red, position=[0, 0, 0])

dl = p3js.DirectionalLight(color='white', position=[0, 1, 5], intensity=1)
al = p3js.AmbientLight(color='#777777')

s =  p3js.Scene(children=[m_tet, m_box, al])

cam = p3js.PerspectiveCamera(position=[2, 3, 2], up=[0, 0, 1], children=[dl])

renderer = p3js.Renderer(camera=cam, scene=s, controls=[p3js.OrbitControls(controlling=cam)])
display(renderer)
```

**Comment by jasongrout** [comment]
It looks like we are not correctly computing the normal vectors for geometries on construction. I'm taking a look at this in #80 with the other geometry work there. Thanks for reporting this!

**Comment by jrsmith3** [comment]
👍🏻👍🏻 thanks!
