### ISSUE TITLE
HTML export

### ISSUE THREAD

**Issue by bermanmaxim** [jovyan/pythreejs#78]
Hi,
Sorry for filling in an issue for this question. I was wondering if there is a way to export the outputs created by this library to a standalone html, or if it's better to directly work with three.js for that use.

**Comment by SylvainCorlay** [comment]
@bermanmaxim yes, it is possible. You can check out the example on http://jupyter.org/widgets for example.

You can find the instructions to do so in the ipywidgets documentation.

**Comment by bermanmaxim** [comment]
Ok thanks, I'll give it a look.

**Comment by nlgranger** [comment]
Hi @SylvainCorlay.
Is the liked page still valid? I do not understand how it relates to this issue.
