### ISSUE TITLE
voxel_painter example runs with errors

### ISSUE THREAD

**Issue by karelin** [jovyan/pythreejs#98]
In the example notebook `voxel_painter.ipynb` there are few errors when creating a material (or other object with color).

As far as I've find out, the bug is related to use of integer hex value for a color, while in `ipywidgets` library (I have ver. 6.0.0 installed with Anaconda) the string value, like `'blue'` or `'#feb74c'` is expected.

When I've changed color specifications from ints to strings, the example was at least runnable (though with a warning and without interactivity in original three.js demo).

**Comment by vidartf** [comment]
This should now be fixed via #88. Please reopen if there's anything I missed.
