### ISSUE TITLE
 Camera.quaternion not updating scene

### ISSUE THREAD

**Issue by chrisjsewell** [jovyan/pythreejs#99]
Hey, thanks for the great package

I am trying to sync the camera orientation of multiple scenes. However, changing the quaternion of the camera (which I assume is the best way) does not change the scene. Should this be the case?

Here is my minimal use case:

```
from pythreejs import *
import numpy as np
from IPython.display import display

scene = Scene(children=[Mesh(
    geometry=SphereGeometry(radius=0.1),
    material=LambertMaterial(color='red'),
    position=[i,j,0]) for i,j in np.mgrid[0:2,0:2].T.reshape((4,2))]+
              [AmbientLight(color='#777777')])
c = OrthographicCamera(position=[0,0,1],
        left=-2,right=2,top=2,bottom=-2,near=-2,
        children=[DirectionalLight(color='white', 
                    position=[3, 5, 1],intensity=0.5)])
control = TrackballControls(controlling=c)
renderer = Renderer(camera=c, height='400',width='400',
                    scene=scene,controls=[control])
display(renderer)

c.position = [0,1,0] # works
c.quaternion = [1,0,0,0] # doesn't work

```

**Comment by vidartf** [comment]
This should now work on master. If you find that it still does not work as expected, feel free to reopen this. Note the orbit/track controls make a jump for the first move after setting the quaternion to `[1,0,0,0]`. This might be related to the up axis of the camera colliding with that quaternion.
